### ISSUE TITLE
Assemble Data

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/pump_up_the_jam#1]
[MER from Q1](https://drive.google.com/drive/u/0/folders/1D0WFOLZJb4kMPpgiqGCIc-G_lT1tWJ21)

[HFR from 2020.01-2020.04 (Q1)](https://drive.google.com/open?id=1vC2k0rRFXNZP_0Ko9Aim3HNogrfErWYK)

**Comment by achafetz** [comment]
Drop MER data from HFR and then bring back in.

**Comment by jaliasd** [comment]
[completed_file](https://drive.google.com/drive/u/0/folders/1cjsz3Ums9B7CHpuZN3pyO3hhMCXvIRVq)

**Comment by achafetz** [comment]
made adjustments to assembly script: HFR data source, aggregate data, merge to deal with NAs, order vars
