### ISSUE TITLE
Function issue

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/pump_up_the_jam#13]
running into an error here
https://github.com/USAID-OHA-SI/pump_up_the_jam/blob/e5302158d209cb341bf483c3267a86841c047932/Scripts/93_viz_completeness.R#L165-L166

![image](https://user-images.githubusercontent.com/8933069/76897563-5af43f80-686a-11ea-97ad-236c0132fd2a.png)

Something up in the function, `prep_fitline()`
https://github.com/USAID-OHA-SI/pump_up_the_jam/blob/e5302158d209cb341bf483c3267a86841c047932/Scripts/93_viz_completeness.R#L110-L116

**Comment by tessam30** [comment]
added filter `filter(!is.na(completeness)) %>% ` to `prep_fitline` function to resolve.
