### ISSUE TITLE
depict largest site calculation

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/pump_up_the_jam#15]

**Comment by tessam30** [comment]
slide added [here](https://docs.google.com/presentation/d/1JiCI1fz9c4_Ev7RZ49jJz2yN10tDHV9Q_6gT-US-5hQ/edit#slide=id.g719ea48def_0_0) with graphics. Made in Tableau using Botswana TX_CURR.

**Comment by tessam30** [comment]
Added R code to produce plots as well. Folding into 02_datim_flags script.
