### ISSUE TITLE
High Volume Flag

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/pump_up_the_jam#2]
sites that represent ~80% of the TX_CURR denominator

count of high volumes sites as well

**Comment by tessam30** [comment]
Created 02_datim_flags for each indicator. 
Count of high volume sites included as flag. 
See below for variable definitions.

Column |  
-- | --
orgunituid | site id
mech_code | mech code id
fy | fiscal year
indicator | indicator
operatingunit | operating unit (country/region)
mer_targets | MER targets from DATIM
mer_results | MER results from DATIM
mechs_per_site | how many mechanisms per site?
results_no_targets | flag if there are results but no targets
ou_targets | operating unit aggregate targets by indicator
ou_results | operating unit aggregate results by indicator
site_targets_sh | site share of operating unit targets
site_results_sh | site share of operating unit results
flag_targets_sh | flag if a site + mech share for targets is more than threshold
flag_results_sh | flag if a site + mech share for results is more than threshold
ou_total_sites | total number of sites in country for each indicator
run_sum_targets | running sum of target share; used to flag high volumn sites
impflag_targets | flag whether or not a site is high volume target
impflag_targets_count | count of high volume sites for targets per operating unit
impflag_targets_sh | what percent of high volume sites are there per operating unit for   targets
run_sum_results | running sum of results share; used to flag high volume sites
impflag_results | flag whether or not a site is high volume result
impflag_results_count | count of high volume sites for results per operating unit
impflag_results_sh | what percent of high volume sites are there per operating unit for   results
impflag_both | what sites are both high volume results and targets?
